<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <OrchardCoreProjectType>Theme</OrchardCoreProjectType>
  </PropertyGroup>

  <Import Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Module.Targets/Lombiq.MSBuild.Module.Targets.props"
          Condition="'$(NuGetBuild)' != 'true'" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Title>Lombiq Base Theme for Orchard Core (Native CSS)</Title>
    <Copyright>Copyright © 2021, Lombiq Technologies Ltd.</Copyright>
    <Description>Lombiq Base Theme for Orchard Core (Native CSS): Orchard Core theme that contains a layout, zones and Bootstrap CSS base for your stylesheets. Set it as your theme's BaseTheme.</Description>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;Css;Theming</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Orchard-Base-Theme</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Orchard-Base-Theme/blob/dev/Lombiq.BaseTheme.Native/Readme.md</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lombiq.BaseTheme.Core\Lombiq.BaseTheme.Core.csproj" />
  </ItemGroup>

  <Import Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Module.Targets/Lombiq.MSBuild.Module.Targets.targets"
          Condition="'$(NuGetBuild)' != 'true'" />

</Project>
