<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.OrchardCore.Theme.Sdk/Sdk/Import.props" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.props" Sdk="Lombiq.MSBuild.OrchardCore.Theme.Sdk" Version="1.0.1-alpha.6.osoe-1208" />

  <PropertyGroup>
    <IsLombiqProject>true</IsLombiqProject>
    <Title>Lombiq Base Theme for Orchard Core (Native CSS)</Title>
    <CopyrightYear>2021</CopyrightYear>
    <DescriptionBody>Orchard Core theme that contains a layout, zones and Bootstrap CSS base for your stylesheets. Set it as your theme's BaseTheme.</DescriptionBody>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;Css;Theming</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Orchard-Base-Theme</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Orchard-Base-Theme/blob/dev/Lombiq.BaseTheme.Native/Readme.md</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lombiq.BaseTheme.Core\Lombiq.BaseTheme.Core.csproj" />
  </ItemGroup>

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.OrchardCore.Theme.Sdk/Sdk/Import.targets" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.targets" Sdk="Lombiq.MSBuild.OrchardCore.Theme.Sdk" Version="1.0.1-alpha.6.osoe-1208" />
</Project>
